# Generated by Django 3.1.8 on 2021-05-13 05:35

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='post name')),
                ('slug', models.SlugField(verbose_name='sluug')),
                ('date_created', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('accessory_level', models.IntegerField(default=2, verbose_name='уровень доступа')),
                ('attachment', models.ManyToManyField(related_name='post_attachment', to='info.Attachment', verbose_name='post_attachment')),
            ],
        ),
    ]
