# Generated by Django 3.1.8 on 2021-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hosting_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видеохостинге'),
        ),
    ]
