# Generated by Django 3.1.8 on 2021-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210513_0948'),
        ('blog', '0002_post_hosting_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='accessory_level',
            field=models.IntegerField(choices=[(1, 'Бесплатный'), (2, 'По подписке'), (3, 'Покупка')], default=2, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ManyToManyField(related_name='post_attachment', to='info.Attachment', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(verbose_name='Кодовое название'),
        ),
    ]
