# Generated by Django 3.1.8 on 2021-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210513_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accessory_level',
            field=models.IntegerField(choices=[(1, 'Бесплатный'), (2, 'По подписке'), (3, 'Покупка')], verbose_name='Уровень доступа'),
        ),
    ]
