# Generated by Django 3.1.8 on 2021-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210515_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='post',
            name='accessory_level',
            field=models.IntegerField(choices=[(1, 'Бесплатный'), (2, 'По подписке')], verbose_name='Уровень доступа'),
        ),
    ]
