# Generated by Django 3.1.8 on 2021-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210513_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Базовая подписка'), (2, 'Продвинутая подписка'), (3, 'PRO подписка')], default=1, verbose_name='План подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'Teacher')], verbose_name='Тип пользователя'),
        ),
    ]
