# Generated by Django 3.1.8 on 2021-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210513_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(verbose_name='Тип пользователя'),
        ),
    ]
