# Generated by Django 3.1.8 on 2021-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210515_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.IntegerField(choices=[(1, 'Базовая подписка'), (2, 'Продвинутая подписка'), (3, 'PRO подписка')], default=1, verbose_name='План подписки'),
        ),
    ]
