# Generated by Django 3.1.8 on 2021-05-15 09:07

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210515_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=unixtimestampfield.fields.UnixTimeStampField(default='0'),
            preserve_default=False,
        ),
    ]
