# Generated by Django 3.1.8 on 2021-05-15 15:59

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210515_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, verbose_name='Время оплаты'),
        ),
    ]
