# Generated by Django 3.1.8 on 2021-05-13 05:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprocesses',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_process_parent', to='info.educationprocesses', verbose_name='education_process'),
        ),
        migrations.AlterField(
            model_name='learningsubjects',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='info.learningsubjects', verbose_name='parent_category'),
        ),
        migrations.AlterField(
            model_name='lessontheme',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_theme_parent', to='info.lessontheme', verbose_name='lesson_theme_parent'),
        ),
        migrations.AlterField(
            model_name='lessontypes',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_types_parent', to='info.lessontypes', verbose_name='lesson_types'),
        ),
    ]
