# Generated by Django 3.1.8 on 2021-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210513_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationprocesses',
            options={'verbose_name': 'Познавательный процесс', 'verbose_name_plural': 'Познавательные процессы'},
        ),
        migrations.AlterField(
            model_name='educationprocesses',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='learningrange',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='learningsubjects',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='lessontheme',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='lessontypes',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
        migrations.AlterField(
            model_name='tasktypes',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Отобразить'),
        ),
    ]
