# Generated by Django 3.1.8 on 2021-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210513_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео'), ('AUDIO', 'Аудио'), ('DOCUMENT', 'Документ'), ('PRESENTATION', 'Презентация')], max_length=15, verbose_name='Тип файла'),
        ),
    ]
