# Generated by Django 3.1.8 on 2021-05-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210515_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningrange',
            options={'verbose_name': 'Период обучения', 'verbose_name_plural': 'Период обучения'},
        ),
        migrations.AlterModelOptions(
            name='learningsubjects',
            options={'verbose_name': 'Предмет обучения', 'verbose_name_plural': 'Предметы обучения'},
        ),
        migrations.AlterModelOptions(
            name='lessontypes',
            options={'verbose_name': 'Тип игры', 'verbose_name_plural': 'Типы игры'},
        ),
    ]
