# Generated by Django 3.1.8 on 2021-05-13 05:35

import apps.utils.func
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('preview', models.ImageField(upload_to=apps.utils.func.card_attachment, verbose_name='Превью карточки')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('full_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('valute', models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('RUB', 'RUB')], max_length=3, verbose_name='Валюта')),
                ('attachment', models.FileField(upload_to=apps.utils.func.card_attachment, verbose_name='Вложение')),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.utils.func.card_attachment, verbose_name='Вложенное видео')),
                ('hosting_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видеохостинге')),
                ('accessory_level', models.CharField(choices=[('1', 'Покупка'), ('2', 'Подписка'), ('3', 'PRO  аккаунт')], max_length=10, verbose_name='Уровень доступа')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('duration', models.CharField(max_length=100, verbose_name='lesson duration')),
                ('age', models.CharField(max_length=100, verbose_name='Age')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название плана')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
        migrations.CreateModel(
            name='PlanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядковый номер в плане')),
            ],
            options={
                'verbose_name': 'Карточка в плане',
                'verbose_name_plural': 'Карточки в плане',
            },
        ),
        migrations.CreateModel(
            name='PurchasedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_purcased_card', to='lessons.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Купленная карточка',
                'verbose_name_plural': 'Купленные карточки',
            },
        ),
    ]
