# Generated by Django 3.1.8 on 2021-05-13 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purcased_card', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='plancard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_plancard', to='lessons.card', verbose_name='Карточка плана'),
        ),
        migrations.AddField(
            model_name='plancard',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_plancard', to='lessons.plan', verbose_name='План карточки'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cards',
            field=models.ManyToManyField(related_name='plan_cards', through='lessons.PlanCard', to='lessons.Card', verbose_name='Карточки'),
        ),
        migrations.AddField(
            model_name='plan',
            name='groups',
            field=models.ManyToManyField(related_name='plan_groups', to='lessons.Group', verbose_name='Группы плана'),
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='education_process',
            field=models.ManyToManyField(related_name='handbook_education_process', to='info.EducationProcesses', verbose_name='Познавательные процессы'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='learning_themes',
            field=models.ManyToManyField(related_name='handbook_leargning_theme', to='info.LessonTheme', verbose_name='Темы занятия'),
        ),
        migrations.AddField(
            model_name='handbook',
            name='learning_types',
            field=models.ManyToManyField(related_name='handbook_leargning_type', to='info.LessonTypes', verbose_name='Виды задания'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(related_name='collection_card', to='lessons.Card', verbose_name='Карточки в коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collection', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_type', to='info.tasktypes', verbose_name='card_type'),
        ),
        migrations.AddField(
            model_name='card',
            name='education_process',
            field=models.ManyToManyField(related_name='card_education_process', to='info.EducationProcesses', verbose_name='Познавательные процессы'),
        ),
        migrations.AddField(
            model_name='card',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites_card', to=settings.AUTH_USER_MODEL, verbose_name='Избранное людей'),
        ),
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(related_name='card_image_attachments', to='info.Attachment'),
        ),
        migrations.AddField(
            model_name='card',
            name='learning_range',
            field=models.ManyToManyField(related_name='card_leargning_range', to='info.LearningRange', verbose_name='Периоды обучения'),
        ),
        migrations.AddField(
            model_name='card',
            name='learning_subjects',
            field=models.ManyToManyField(related_name='card_leargning_subjects', to='info.LearningSubjects', verbose_name='Предметы карточки'),
        ),
        migrations.AddField(
            model_name='card',
            name='learning_themes',
            field=models.ManyToManyField(related_name='card_leargning_theme', to='info.LessonTheme', verbose_name='Темы занятия'),
        ),
        migrations.AddField(
            model_name='card',
            name='learning_types',
            field=models.ManyToManyField(related_name='card_leargning_type', to='info.LessonTypes', verbose_name='Виды задания '),
        ),
    ]
