# Generated by Django 3.1.8 on 2021-05-15 08:59

import apps.utils.func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210513_0948'),
        ('lessons', '0002_auto_20210513_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.utils.func.card_attachment, verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='card_image_attachments', to='info.Attachment'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.func.card_attachment, verbose_name='Превью карточки'),
        ),
        migrations.AlterField(
            model_name='group',
            name='age',
            field=models.CharField(max_length=100, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
