# Generated by Django 3.1.8 on 2021-05-15 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0003_auto_20210515_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites_card', to=settings.AUTH_USER_MODEL, verbose_name='Избранное людей'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='plancard',
            unique_together={('plan', 'card', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasedcard',
            unique_together={('user', 'card')},
        ),
    ]
